[versions]
agp = "8.2.0-beta05"
appcompat = "1.6.1"
coilVersion = "2.4.0"
fuzzywuzzy = "1.4.0"
glideCompose = "1.0.0-beta1-SNAPSHOT"
exifinterface = "1.3.6"
glideSvg = "4.0.2"
glideVersion = "4.16.0"
kotlin = "1.9.10"
kotlinCoroutinesVersion = "1.7.3"
ksp = "1.9.10-1.0.13"
core-ktx = "1.12.0"
junit = "4.13.2"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"
lifecycle-runtime = "2.6.2"
activity-compose = "1.8.0"
compose-bom = "2023.09.01"
hilt = "2.48"
material = "1.10.0"
material3 = "1.2.0-alpha08"
media3Ui = "1.1.1"
media3Exoplayer = "1.1.1"
navigation-runtime-ktx = "2.7.4"
profileinstaller = "1.3.1"
room = "2.6.0-rc01"
accompanist = "0.32.0"
datastore ="1.1.0-alpha05"
zoomable = "1.5.1"

[libraries]
# AndroidX
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-exifinterface = { module = "androidx.exifinterface:exifinterface", version.ref = "exifinterface" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle-runtime" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime" }
androidx-media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3Ui" }
androidx-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3Exoplayer" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-runtime-ktx" }
androidx-navigation-runtime-ktx = { module = "androidx.navigation:navigation-runtime-ktx", version.ref = "navigation-runtime-ktx" }
androidx-profileinstaller = { module = "androidx.profileinstaller:profileinstaller", version.ref = "profileinstaller" }

# Coil
coil-video = { module = "io.coil-kt:coil-video", version.ref = "coilVersion" }
coil-gif = { module = "io.coil-kt:coil-gif", version.ref = "coilVersion" }
coil-svg = { module = "io.coil-kt:coil-svg", version.ref = "coilVersion" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilVersion" }

# Glide
glide-compiler = { module = "com.github.bumptech.glide:ksp", version.ref = "glideVersion" }
glide-avif = { module = "com.github.bumptech.glide:avif-integration", version.ref = "glideVersion" }
glide-compose = { module = "com.github.bumptech.glide:compose", version.ref = "glideCompose" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glideVersion" }
glide-svg = { module = "com.github.qoqa:glide-svg", version.ref = "glideSvg" }

# Compose
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
compose-lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle-runtime" }
compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
compose-material3-window-size = { group = "androidx.compose.material3", name = "material3-window-size-class", version.ref = "material3" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-util = { group = "androidx.compose.ui", name = "ui-util" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name= "ui-tooling-preview" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }

# Compose-shimmer
compose-shimmer = { group = "com.valentinilk.shimmer", name = "compose-shimmer", version = "1.0.5"}

# Compose Tests
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }

# Dagger
dagger-hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
dagger-hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
androidx-hilt-compiler = { group = "androidx.hilt", name = "hilt-compiler", version = "1.0.0" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version = "1.1.0-alpha01" }

# Room
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }

# Datastore
datastore-prefs = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }

# Accompanists
accompanist-systemuicontroller = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanist" }
accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanist" }

# Zoomable
zoomable = { module = "net.engawapg.lib:zoomable", version.ref = "zoomable" }

# Kotlinx
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinCoroutinesVersion" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinCoroutinesVersion" }

# View-based AndroidX
material = { module = "com.google.android.material:material", version.ref = "material" }

# Fuzzy Search
fuzzywuzzy = { module = "me.xdrop:fuzzywuzzy", version.ref = "fuzzywuzzy" }

# Tests
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
androidTest = { id = "com.android.test", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kspAndroid = { id = "com.google.devtools.ksp", version.ref = "ksp" }
roomPlugin = { id = "androidx.room", version.ref = "room" }
hiltAndroid = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
baselineProfilePlugin = { id = "androidx.baselineprofile", version = "1.2.0-rc02" }
[bundles]

