[versions]
agp = "8.3.1"
benchmarkMacroJunit4 = "1.2.3"
composeCompiler = "1.5.11"
appcompat = "1.6.1"
coilVersion = "3.0.0-alpha06"
fuzzywuzzy = "1.4.0"
exifinterface = "1.3.7"
gpuimage = "2.1.0"
jxlCoder = "1.11.1"
kotlin = "1.9.23"
kotlinCoroutinesVersion = "1.8.0"
ksp = "1.9.23-1.0.19"
core-ktx = "1.12.0"
junit = "4.13.2"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"
lifecycle-runtime = "2.7.0"
activity-compose = "1.8.2"
compose-bom = "2024.03.00"
hilt = "2.51"
material = "1.11.0"
material3 = "1.2.1"
media3Ui = "1.3.0"
media3Exoplayer = "1.3.0"
navigation-runtime-ktx = "2.7.7"
pinchzoomgrid = "0.0.5"
profileinstaller = "1.3.1"
room = "2.6.1"
accompanist = "0.34.0"
datastore = "1.1.0-beta02"
uiautomator = "2.3.0"
zoomable = "1.6.1"
zoomableImageCoil = "0.8.0"

[libraries]
# AndroidX
androidx-benchmark-macro-junit4 = { module = "androidx.benchmark:benchmark-macro-junit4", version.ref = "benchmarkMacroJunit4" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-exifinterface = { module = "androidx.exifinterface:exifinterface", version.ref = "exifinterface" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime" }
androidx-media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3Ui" }
androidx-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3Exoplayer" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-runtime-ktx" }
androidx-profileinstaller = { module = "androidx.profileinstaller:profileinstaller", version.ref = "profileinstaller" }

# Coil
androidx-uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "uiautomator" }
coil-video = { module = "io.coil-kt.coil3:coil-video", version.ref = "coilVersion" }
coil-gif = { module = "io.coil-kt.coil3:coil-gif", version.ref = "coilVersion" }
coil-svg = { module = "io.coil-kt.coil3:coil-svg", version.ref = "coilVersion" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coilVersion" }
coil-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coilVersion" }

# Compose
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
compose-lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle-runtime" }
compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
compose-material3-window-size = { group = "androidx.compose.material3", name = "material3-window-size-class", version.ref = "material3" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name= "ui-tooling-preview" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }

# Compose-shimmer
compose-shimmer = { group = "com.valentinilk.shimmer", name = "compose-shimmer", version = "1.2.0"}

# Compose Tests
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }

# Dagger
dagger-hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
dagger-hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
androidx-hilt-compiler = { group = "androidx.hilt", name = "hilt-compiler", version = "1.2.0" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version = "1.2.0" }

# Room
gpuimage = { module = "jp.co.cyberagent.android:gpuimage", version.ref = "gpuimage" }
jxl-coder-coil = { module = "com.github.awxkee:jxl-coder-coil", version.ref = "jxlCoder" }
pinchzoomgrid = { module = "io.github.dokar3:pinchzoomgrid", version.ref = "pinchzoomgrid" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }

# Datastore
datastore-prefs = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }

# Accompanists
accompanist-systemuicontroller = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanist" }
accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanist" }
accompanist-drawablepainter = { module = "com.google.accompanist:accompanist-drawablepainter", version.ref = "accompanist" }

# Zoomable
zoomable = { module = "net.engawapg.lib:zoomable", version.ref = "zoomable" }

# Kotlinx
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinCoroutinesVersion" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinCoroutinesVersion" }

# View-based AndroidX
material = { module = "com.google.android.material:material", version.ref = "material" }

# Fuzzy Search
fuzzywuzzy = { module = "me.xdrop:fuzzywuzzy", version.ref = "fuzzywuzzy" }

# Tests
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
zoomable-image-coil = { module = "me.saket.telephoto:zoomable-image-coil", version.ref = "zoomableImageCoil" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
androidTest = { id = "com.android.test", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kspAndroid = { id = "com.google.devtools.ksp", version.ref = "ksp" }
roomPlugin = { id = "androidx.room", version.ref = "room" }
hiltAndroid = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
baselineProfilePlugin = { id = "androidx.baselineprofile", version = "1.2.3" }
[bundles]

